### ISSUE TITLE
[18.0.1] - Error: export 'takeUntil' (imported as 'takeUntil$1') was not found in 'rxjs'

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-angular-examples#195]
igniteui-angular package version 18.0.1

./node_modules/igniteui-angular/fesm2022/igniteui-angular.mjs:99603:59-70 - Error: export 'takeUntil' (imported as 'takeUntil$1') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrame, animationFrameScheduler, asap, asapScheduler, async, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queue, queueScheduler, race, range, scheduled, throwError, timer, using, zip)

**Comment by dobromirts** [comment]
Resolved in package version 18.0.6

**Comment by Masa8500** [comment]
I have the same problem.  At first I update the @infragistics/igniteui-angular -package to newest 17 version and i got the same error (different line number) Then i updated to newest 18 version i still get the error. I removed the node_modules folder, deleted the package-lock.json -file and installed npm packages again and it did not help.

I am pretty sure that that at the moment igniteui-angular is not compatible with rxjs < 7 -version.
